spring.application.name=job-service
server.port=8086

# MySQL Configuration (TiDB Cloud)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=3utXacfbRoTt2ay.root
spring.datasource.password=LbgcFSh3LDgvxXgY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Error handling
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-message=always

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka
spring.cloud.service-url.defaultZone=https://projectbackend-serviceregistery-1.onrender.com/eureka/
eureka.instance.prefer-ip-address=false

# Internal security
internal.security.key=Lalit-Super-Secret-Key-2026